### ISSUE TITLE
[Adding Feature] Gradation with class color at objective tracker

### ISSUE THREAD

**Issue by hobulian** [fang2hou/ElvUI_WindTools#226]
Now objective tracker has only option for gradation with custom color, solid color(which has class or custom).

Think gradation will be nice to also have class color as it's first or end color.

Can you add this one?

Also hope there be shadow custom for objective tracker's header text.

**Comment by fang2hou** [comment]
It's possible in coding but I prefer to not add it because the option will be confused for many users.

The easiest way is that setting the color to your class color in custom color configuration.

Actually the gradient color setting already be confusing for many users. Many people tell me that they cannot understand the usage and the purpose of these options.

I make this addon for most players, if most users not need the feature or module, I will just delete them. So for further more customization if you need, I suggest you do some simple hooks to the bar color change functions.
All my module also provide accessibility to the frames to developers. Creating a WA, hook ing some functions after WindTools loaded is the best way to create and share your own style. If you have any code problem you can also go to discord for help.
