### ISSUE TITLE
Event trackers on maps

### ISSUE THREAD

**Issue by Pairaka** [fang2hou/ElvUI_WindTools#286]
The trackers for the Community Feasts and Siege on Dragonbane Keep are very nice to have, however, the way they display on the map in the Quest Log is a bit ugly. It would be nice to be able to adjust the placement of them as well as get rid of the outline on the box. An option to either move the trackers onto the map or just not have them display on the quest log at all would be appreciated. 

![WoWScrnShot_121522_084715](https://user-images.githubusercontent.com/39540618/207875806-dfeb8026-fdfc-49ea-981c-d2d7721206fc.jpg)

Also, on the full size world map, the placement interferes with faction selection button. You can also see the white outline of the box they are in and it looks unsightly: 

![WoWScrnShot_121522_085213](https://user-images.githubusercontent.com/39540618/207876538-1e3908d2-7d32-43b2-88f6-38f092e47dcb.jpg)

**Comment by fang2hou** [comment]
The place you want to move is where many addon already used, for example, world quest tracker.
I considered many place to put new trackers, but finally add a new little frame is the safest way.
And yeah, maybe it looks not good in Blizzard style world map, because the module is aimed to work with ElvUI skin not blizzard.

I will add a little option for changing the y offset of this, it may provide the style in your example.
